import os

import streamlit as st
from dotenv import load_dotenv

from src.generator import generate_with_fallback
from src.models import CandidateProfile
from src.negotiation import build_private_negotiation_note
from src.privacy import build_cloud_payload

load_dotenv()

st.set_page_config(page_title="Split-Brain Cover Letter", page_icon="🧠", layout="wide")

st.title("🧠 Split-Brain Cover Letter")
st.caption("Cloud quality + local privacy + offline fallback")

with st.expander("How privacy works", expanded=False):
    st.markdown(
        """
- 🔒 **Local only:** name, email, phone, current employer, current salary, desired salary and currency.
- ☁️ **Cloud-eligible:** generic role, target role/company, experience, skills, achievements, motivation and job posting — **after deterministic redaction**.
- The cloud payload is created by an explicit allowlist in code. A model never decides what leaves the device.
- If the cloud call fails, the app tries Ollama locally. If Ollama is unavailable, a deterministic template still produces a usable letter.
        """
    )

with st.form("cover_form"):
    st.subheader("1. Private data — stays on this device")
    c1, c2 = st.columns(2)
    with c1:
        full_name = st.text_input("Full name 🔒", placeholder="Emily Example")
        email = st.text_input("Email 🔒")
        current_employer = st.text_input("Current employer 🔒")
        current_salary = st.number_input("Current salary 🔒", min_value=0.0, step=100.0)
    with c2:
        phone = st.text_input("Phone 🔒")
        currency = st.selectbox("Currency 🔒", ["GTQ", "USD", "EUR", "Other"])
        desired_salary = st.number_input("Desired salary 🔒", min_value=0.0, step=100.0)

    st.subheader("2. Professional data — may go to cloud after redaction")
    c3, c4 = st.columns(2)
    with c3:
        current_role_generic = st.text_input("Current role (generic)", placeholder="Program coordinator / Mechatronics engineer")
        target_role = st.text_input("Target role", placeholder="Program Coordinator")
        target_company = st.text_input("Target company")
        years_experience = st.number_input("Years of relevant experience", min_value=0, max_value=60, step=1)
    with c4:
        skills = st.text_area("Skills", placeholder="project coordination, event logistics, stakeholder communication")
        achievements = st.text_area("Achievements", placeholder="Organized STEM events and coordinated speakers and participants...")
        motivation = st.text_area("Why this role/company?")
        tone = st.selectbox("Tone", ["professional and warm", "concise and direct", "enthusiastic but professional"])

    job_posting = st.text_area("Job posting (optional)", height=180)
    prefer_cloud = st.checkbox("Use cloud model when available", value=True)
    submitted = st.form_submit_button("Generate cover letter")

if submitted:
    profile = CandidateProfile(
        full_name=full_name,
        email=email,
        phone=phone,
        current_employer=current_employer,
        current_salary=current_salary,
        desired_salary=desired_salary,
        currency=currency,
        current_role_generic=current_role_generic,
        target_role=target_role,
        target_company=target_company,
        years_experience=int(years_experience),
        skills=skills,
        achievements=achievements,
        motivation=motivation,
        job_posting=job_posting,
        tone=tone,
    )

    payload, audit = build_cloud_payload(profile)
    result = generate_with_fallback(profile, prefer_cloud=prefer_cloud)
    negotiation = build_private_negotiation_note(profile)

    left, right = st.columns([2, 1])
    with left:
        st.subheader("Cover letter")
        st.text_area("Ready to copy", result.letter, height=430, label_visibility="collapsed")
        st.caption(f"Generated by: **{result.source}**")
        if result.detail:
            st.caption(result.detail)

    with right:
        st.subheader("Private negotiation note 🔒")
        st.info(negotiation.note)
        st.caption("This note is computed locally and is never included in the cloud payload.")

    with st.expander("Audit: exactly what would be sent to cloud"):
        st.json(payload)
        st.write(f"Redactions made before cloud: **{audit.redactions}**")
        if audit.redacted_categories:
            st.write("Categories:", ", ".join(audit.redacted_categories))

    st.download_button(
        "Download letter as .txt",
        data=result.letter,
        file_name="cover_letter.txt",
        mime="text/plain",
    )

st.divider()
st.caption(
    "Configuration: OPENAI_API_KEY= "
    + ("configured" if os.getenv("OPENAI_API_KEY") else "not configured")
    + " · Ollama model="
    + os.getenv("OLLAMA_MODEL", "qwen3:4b")
)
